fix: support guzzle psr 2.x
guzzle/oauth-subscriber pull request #90
Opened 2021-07-09 03:19 UTC by atymic

2021-07-09 09:45 UTC, GrahamCampbell requested changes

2021-07-09 09:45 UTC, GrahamCampbell commented on composer.json
> +        "guzzlehttp/psr7": "^1.8 || ^2.0"
```suggestion
        "guzzlehttp/psr7": "^1.7|^2.0"
```

2021-07-12 11:59 UTC, GrahamCampbell commented
cc @Nyholm can you give me push access to this repo please, and related ones.

2021-07-12 12:00 UTC, GrahamCampbell approved these changes

2021-07-12 21:22 UTC, Nyholm commented
Thank you

2021-07-12 21:22 UTC, merged